# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afc697e6f467e4019fa4150182197a887dcc0094b13466560fe19a24d1a3d7ff13bc82cb3d0fda634c1058e0517ca70e36589091bae84cf2fcb28f056cafa462

test:
  secret_key_base: 473d110065f70d359d27256a1bced2bc3bf3ae5d6e113e63c9f8d6b36622ef382ad57278261da13f27011e1540a92ff023215252ce0e6177d93cc286f4d4de49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
